### ISSUE TITLE
Full-proof guide to work with GitHub pages

### ISSUE THREAD

**Issue by yairchu** [ChrisPenner/slick-template#3]
I tried following the instructions to host my site with GitHub Pages but got it to look [like this](https://yairchu.github.io/blog/) rather than with all the nice images and styles.. It looks like it links an image at `/images/github-logo.png` while it is available at `/blog/images/github-logo.png`. I also tried to rename the repository to `yairchu.github.io` but then the repo settings did not offers the option to use the `docs` folder to be the pages folder.

**Comment by ChrisPenner** [comment]
Thanks for the reports; I have my sites set up with a custom domain so I suppose I should have tested this a little more carefully. What we can do is rig up the templates to use the [baseUrl](https://github.com/ChrisPenner/slick-template/blob/master/app/Main.hs#L27) for image paths rather than using the site root `/`, then you can set your baseUrl to `https://yairchu.github.io/blog/` and it should work out I think.

I'll fix that as soon as I have a minute free, but if you get around to it first feel free. Shouldn't be too much work :)

Sorry you're running into all the rough edges!

**Comment by yairchu** [comment]
What I ended up doing, which perhaps is a way to solve things? Is have the `master` branch contain the contents of the `docs` folder and have the source in the `src` branch. See https://github.com/yairchu/yairchu.github.io/blob/src/publish.sh

**Comment by glebec** [comment]
I think this should still be open since following the README as-is currently does not work – e.g. if I use GH pages to host a site for a repo `some-demo` at `https://glebec.github.io/some-demo`, then the absolute image/JS/CSS URLs all try to load from `https://glebec.github.io/`.
